---
- name: Clone goenv
  git:
    repo: https://github.com/syndbg/goenv.git
    dest: '{{ goenv_path }}'
    update: '{{ goenv_update_git_install }}'

- name: Add to .bashrc
  become: yes
  lineinfile:
    path: ~/.bashrc
    line: . ~/.pyenvrc
  with_items: '{{ pyenv_users }}'

- name: Install Python
  shell: . ~/.pyenvrc && pyenv install {{ item | quote }}
  environment:
    PYTHON_CONFIGURE_OPTS: '{{ pyenv_python_configure_opts }}'
  with_items: '{{ pyenv_python_versions }}'
- name: Set goenv global
  shell: goenv global {{ goenv_global }} && goenv rehash
