---
- name: Clone goenv
  git:
    repo: https://github.com/syndbg/goenv.git
    dest: '{{ goenv_path }}'
    update: true

- name: Add to .profile
  ansible.builtin.blockinfile:
    path: ~/.profile
    insertafter: EOF
    create: true
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    block: |
      export GOENV_ROOT="${HOME}/.goenv"
      export PATH="${GOENV_ROOT}/bin:${PATH}"
      eval "$(goenv init -)"
      export PATH="${GOROOT}/bin:${PATH}"
      export PATH="${PATH}:${GOPATH}/bin"

- name: Install Go
  ignore_errors: true
  shell: >
    . ~/.profile 
    && echo | goenv install {{ item | quote }} 
    && goenv rehash
  loop: '{{ go_versions }}'

- name: Set goenv global
  ignore_errors: true
  shell: >
    . ~/.profile 
    && yes n | goenv global {{ go_versions | join(' ') }}
    && goenv rehash
