---
- name: Install prerequisites
  become: yes
  apt:
    update_cache: true
    install_recommends: false
    pkg:
      - autoconf
      - bison
      - build-essential
      - libdb-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - libncurses5-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - zlib1g-dev

- name: Clone pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: '{{ pyenv_path }}'
    update: '{{ pyenv_update_git_install }}'

- name: Write .pyenvrc for users
  become: yes
  become_user: '{{ item }}'
  template:
    src: .pyenvrc.j2
    dest: '~{{ item }}/.pyenvrc'
    backup: yes
    mode: 'u=rw,go=r'
  with_items: '{{ pyenv_users }}'

- name: Add .pyenvrc to .bashrc
  become: yes
  become_user: '{{ item }}'
  lineinfile:
    path: ~/.bashrc
    line: . ~/.pyenvrc
  with_items: '{{ pyenv_users }}'

- name: Install Python
  shell: . ~/.pyenvrc && pyenv install {{ item | quote }}
  environment:
    PYTHON_CONFIGURE_OPTS: '{{ pyenv_python_configure_opts }}'
  with_items: '{{ pyenv_python_versions }}'
- name: Set pyenv global
  shell: . ~/.pyenvrc && pyenv global {{ pyenv_global }} && pyenv rehash
  when: pyenv_global is defined
