---
- name: Install prerequisites
  become: true
  apt:
    update_cache: true
    install_recommends: false
    pkg:
      - autoconf
      - bison
      - build-essential
      - curl
      - git
      - libbz2-dev
      - libdb-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline6-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libyaml-dev
      - llvm
      - python3-openssl
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev

- name: Clone pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: '{{ pyenv_path }}'
    update: true

- name: Add to .profile
  ansible.builtin.blockinfile:
    path: ~/.profile
    insertafter: EOF
    create: true
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    block: |
      export PYENV_ROOT="${HOME}/.pyenv"
      export PATH="${PYENV_ROOT}/bin:${PATH}"
      eval "$(pyenv init --path)"

- name: Install Python
  ignore_errors: true
  shell: >
    . ~/.profile 
    && echo | pyenv install {{ item | quote }}  
    && pyenv rehash
  environment:
    PYTHON_CONFIGURE_OPTS: '{{ python_configure_opts }}'
  loop: '{{ python_versions }}'


- name: Set pyenv global
  ignore_errors: true
  shell: >
    . ~/.profile  
    && echo | pyenv global {{ python_versions | join(' ') }}  
    && pyenv rehash
